### ISSUE TITLE
DeepL funktioniert nicht richtig in CS

### ISSUE THREAD

**Issue by andrej-repisky** [trovu/trovu-data#19]
Die Ausgangsprache ist nicht CS, sonder DE. Idealerweise sollte sie aber erkannt werden, wie bei `gtr`.

Schritte
- https://trovu.net/index.html#github=andrej-repisky öffnen
- Anfrage tippen: "dlru Jmenuji se Julie."

DeepL wird geöffnet, aber der Text wird nicht übersetzt.

**Comment by georgjaehnig** [comment]
`dlru` is one of the old DeepL commands, it's going to be removed with the restructuring of the dictionaries.

The current shortcut is `dpl {$word}`. It will auto-detect the source language and use `language:` from your [config](https://github.com/andrej-repisky/trovu-data-user/blob/master/config.yml) as the target language.

**Comment by andrej-repisky** [comment]
`dpl` geht bei mir nicht.

**Comment by georgjaehnig** [comment]
Der Shortcut ist recht neu. Hast Du einen `reload` probiert?

**Comment by georgjaehnig** [comment]
Please reopen if problem persists.
