### ISSUE TITLE
en.zh broken

### ISSUE THREAD

**Issue by ospalh** [trovu/trovu-data#32]
Looks like the hanzi you type with the keyword en.zh don’t get thu to the dictionary.
It shows a Chinese translation of the phrase »{query}« instead

**Comment by georgjaehnig** [comment]
What's the URL you get redirected to?

**Comment by ospalh** [comment]
`https://www.mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb={query}`
With everything but the `{query}` the correct link.

**Comment by georgjaehnig** [comment]
Closed with #33 .
